site_name: Fluufff IT

repo_url: https://github.com/Fluufff/handbook 
edit_uri: edit/main/docs/

theme:
  name: terminal
  palette: gruvbox_dark
  features:
  - revision.date
  - revision.history
  - footer.prev_next
  - navigation.side.indexes

plugins:
- search
- git-revision-date
